export const SITE_CONFIG = {
  name: 'A4 AutoPost',
  description: 'AI-Powered Social Media Management & Automated Multi-Platform Publishing',
  domain: process.env.NEXT_PUBLIC_SITE_URL || 'https://a4autopost.com',
  dashboardUrl: process.env.NEXT_PUBLIC_DASHBOARD_URL || 'https://dashboard.a4autopost.com',
  apiUrl: process.env.NEXT_PUBLIC_API_URL || 'https://api.a4autopost.com/api/v1',
  googleAnalyticsId: process.env.NEXT_PUBLIC_GA_ID || 'G-FJYLP8X6RX',
  twitterHandle: '@a4autopost',
  ogImage: '/logo.png',
  author: 'A4 AutoPost Team',
  keywords: [
    'AI social media manager',
    'social media auto post',
    'content scheduler',
    'multi-platform social publishing',
    'AI caption generator',
    'social media analytics',
    'social queue automation',
  ],
  social: {
    instagram: 'https://www.instagram.com/a4autopost/',
    linkedin: 'https://www.linkedin.com/company/145224167/',
    twitter: 'https://x.com/a4autopost',
    facebook: 'https://www.facebook.com/profile.php?id=61594349112657',
  },
};
